package es.curso.bean;
// Generated 06-nov-2017 19:58:31 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set productoses = new HashSet(0);

	public Categorias() {
	}

	public Categorias(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public Categorias(int id, String nombre, Set productoses) {
		this.id = id;
		this.nombre = nombre;
		this.productoses = productoses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set productoses) {
		this.productoses = productoses;
	}

}
