package es.curso.bean;
// Generated 06-nov-2017 19:58:31 by Hibernate Tools 4.3.5.Final

/**
 * Detallespedido generated by hbm2java
 */
public class Detallespedido implements java.io.Serializable {

	private DetallespedidoId id;
	private Pedidos pedidos;
	private Productos productos;
	private Float precio;
	private Integer unidades;
	private Float descuento;

	public Detallespedido() {
	}

	public Detallespedido(DetallespedidoId id, Pedidos pedidos, Productos productos) {
		this.id = id;
		this.pedidos = pedidos;
		this.productos = productos;
	}

	public Detallespedido(DetallespedidoId id, Pedidos pedidos, Productos productos, Float precio, Integer unidades,
			Float descuento) {
		this.id = id;
		this.pedidos = pedidos;
		this.productos = productos;
		this.precio = precio;
		this.unidades = unidades;
		this.descuento = descuento;
	}

	public DetallespedidoId getId() {
		return this.id;
	}

	public void setId(DetallespedidoId id) {
		this.id = id;
	}

	public Pedidos getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Pedidos pedidos) {
		this.pedidos = pedidos;
	}

	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	public Integer getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Integer unidades) {
		this.unidades = unidades;
	}

	public Float getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Float descuento) {
		this.descuento = descuento;
	}

}
