package es.curso.bean;
// Generated 06-nov-2017 19:58:31 by Hibernate Tools 4.3.5.Final

/**
 * DetallespedidoId generated by hbm2java
 */
public class DetallespedidoId implements java.io.Serializable {

	private int idpedido;
	private int idproducto;

	public DetallespedidoId() {
	}

	public DetallespedidoId(int idpedido, int idproducto) {
		this.idpedido = idpedido;
		this.idproducto = idproducto;
	}

	public int getIdpedido() {
		return this.idpedido;
	}

	public void setIdpedido(int idpedido) {
		this.idpedido = idpedido;
	}

	public int getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(int idproducto) {
		this.idproducto = idproducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetallespedidoId))
			return false;
		DetallespedidoId castOther = (DetallespedidoId) other;

		return (this.getIdpedido() == castOther.getIdpedido()) && (this.getIdproducto() == castOther.getIdproducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpedido();
		result = 37 * result + this.getIdproducto();
		return result;
	}

}
