package es.curso.bean;
// Generated 06-nov-2017 19:58:31 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private int id;
	private String nombre;
	private String cargo;
	private Set pedidoses = new HashSet(0);

	public Empleados() {
	}

	public Empleados(int id) {
		this.id = id;
	}

	public Empleados(int id, String nombre, String cargo, Set pedidoses) {
		this.id = id;
		this.nombre = nombre;
		this.cargo = cargo;
		this.pedidoses = pedidoses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public Set getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set pedidoses) {
		this.pedidoses = pedidoses;
	}

}
