package es.curso.bean;
// Generated 06-nov-2017 19:58:31 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos implements java.io.Serializable {

	private int idpedido;
	private Clientes clientes;
	private Empleados empleados;
	private Empresasenvios empresasenvios;
	private Float importe;
	private String pais;
	private Set detallespedidos = new HashSet(0);

	public Pedidos() {
	}

	public Pedidos(int idpedido, Clientes clientes, Empleados empleados, Empresasenvios empresasenvios) {
		this.idpedido = idpedido;
		this.clientes = clientes;
		this.empleados = empleados;
		this.empresasenvios = empresasenvios;
	}

	public Pedidos(int idpedido, Clientes clientes, Empleados empleados, Empresasenvios empresasenvios, Float importe,
			String pais, Set detallespedidos) {
		this.idpedido = idpedido;
		this.clientes = clientes;
		this.empleados = empleados;
		this.empresasenvios = empresasenvios;
		this.importe = importe;
		this.pais = pais;
		this.detallespedidos = detallespedidos;
	}

	public int getIdpedido() {
		return this.idpedido;
	}

	public void setIdpedido(int idpedido) {
		this.idpedido = idpedido;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Empleados getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Empleados empleados) {
		this.empleados = empleados;
	}

	public Empresasenvios getEmpresasenvios() {
		return this.empresasenvios;
	}

	public void setEmpresasenvios(Empresasenvios empresasenvios) {
		this.empresasenvios = empresasenvios;
	}

	public Float getImporte() {
		return this.importe;
	}

	public void setImporte(Float importe) {
		this.importe = importe;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public Set getDetallespedidos() {
		return this.detallespedidos;
	}

	public void setDetallespedidos(Set detallespedidos) {
		this.detallespedidos = detallespedidos;
	}

}
