package es.curso.bean;
// Generated 06-nov-2017 19:58:31 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private Integer id;
	private Categorias categorias;
	private String nombre;
	private Float precio;
	private Integer existencias;
	private Set detallespedidos = new HashSet(0);

	public Productos() {
	}

	public Productos(Categorias categorias) {
		this.categorias = categorias;
	}

	public Productos(Categorias categorias, String nombre, Float precio, Integer existencias, Set detallespedidos) {
		this.categorias = categorias;
		this.nombre = nombre;
		this.precio = precio;
		this.existencias = existencias;
		this.detallespedidos = detallespedidos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Categorias getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Categorias categorias) {
		this.categorias = categorias;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	public Integer getExistencias() {
		return this.existencias;
	}

	public void setExistencias(Integer existencias) {
		this.existencias = existencias;
	}

	public Set getDetallespedidos() {
		return this.detallespedidos;
	}

	public void setDetallespedidos(Set detallespedidos) {
		this.detallespedidos = detallespedidos;
	}

}
