package es.curso.bean;
// Generated 08-nov-2017 16:35:29 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorias generated by hbm2java
 */
@Entity
@Table(name = "categorias", catalog = "empresa3")
public class Categorias implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set<Productos> productoses = new HashSet<Productos>(0);

	public Categorias() {
	}

	public Categorias(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public Categorias(int id, String nombre, Set<Productos> productoses) {
		this.id = id;
		this.nombre = nombre;
		this.productoses = productoses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorias")
	public Set<Productos> getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set<Productos> productoses) {
		this.productoses = productoses;
	}

}
