package es.curso.bean;
// Generated 08-nov-2017 16:35:29 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresasenvios generated by hbm2java
 */
@Entity
@Table(name = "empresasenvios", catalog = "empresa3")
public class Empresasenvios implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);

	public Empresasenvios() {
	}

	public Empresasenvios(int id) {
		this.id = id;
	}

	public Empresasenvios(int id, String nombre, Set<Pedidos> pedidoses) {
		this.id = id;
		this.nombre = nombre;
		this.pedidoses = pedidoses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresasenvios")
	public Set<Pedidos> getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set<Pedidos> pedidoses) {
		this.pedidoses = pedidoses;
	}

}
