package es.curso.bean;
// Generated 08-nov-2017 16:35:29 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name = "productos", catalog = "empresa3")
public class Productos implements java.io.Serializable {

	private Integer id;
	private Categorias categorias;
	private String nombre;
	private Float precio;
	private Integer existencias;
	private Set<Detallespedido> detallespedidos = new HashSet<Detallespedido>(0);

	public Productos() {
	}

	public Productos(Categorias categorias) {
		this.categorias = categorias;
	}

	public Productos(Categorias categorias, String nombre, Float precio, Integer existencias,
			Set<Detallespedido> detallespedidos) {
		this.categorias = categorias;
		this.nombre = nombre;
		this.precio = precio;
		this.existencias = existencias;
		this.detallespedidos = detallespedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategoria", nullable = false)
	public Categorias getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Categorias categorias) {
		this.categorias = categorias;
	}

	@Column(name = "nombre", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio", precision = 12, scale = 0)
	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	@Column(name = "existencias")
	public Integer getExistencias() {
		return this.existencias;
	}

	public void setExistencias(Integer existencias) {
		this.existencias = existencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
	public Set<Detallespedido> getDetallespedidos() {
		return this.detallespedidos;
	}

	public void setDetallespedidos(Set<Detallespedido> detallespedidos) {
		this.detallespedidos = detallespedidos;
	}

}
