package es.curso.bean;
// Generated 08-nov-2017 16:35:29 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "empresa3")
public class Usuarios implements java.io.Serializable {

	private String login;
	private String pass;

	public Usuarios() {
	}

	public Usuarios(String login, String pass) {
		this.login = login;
		this.pass = pass;
	}

	@Id

	@Column(name = "login", unique = true, nullable = false, length = 50)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "pass", nullable = false, length = 50)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

}
