package es.curso.sh4.pojo;
// Generated 03-mar-2017 9:31:35 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name = "clientes", catalog = "empresa3")
public class Clientes implements java.io.Serializable {

	private String idcliente;
	private String nombre;
	private String pais;
	private Boolean carnet;
	private Boolean musica;
	private Boolean deporte;
	private Boolean cine;
	private Boolean montanya;
	private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);

	public Clientes() {
	}

	public Clientes(String idcliente) {
		this.idcliente = idcliente;
	}

	public Clientes(String idcliente, String nombre, String pais, Boolean carnet, Boolean musica, Boolean deporte,
			Boolean cine, Boolean montanya, Set<Pedidos> pedidoses) {
		this.idcliente = idcliente;
		this.nombre = nombre;
		this.pais = pais;
		this.carnet = carnet;
		this.musica = musica;
		this.deporte = deporte;
		this.cine = cine;
		this.montanya = montanya;
		this.pedidoses = pedidoses;
	}

	@Id

	@Column(name = "idcliente", unique = true, nullable = false, length = 10)
	public String getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(String idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "pais", length = 30)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "carnet")
	public Boolean getCarnet() {
		return this.carnet;
	}

	public void setCarnet(Boolean carnet) {
		this.carnet = carnet;
	}

	@Column(name = "musica")
	public Boolean getMusica() {
		return this.musica;
	}

	public void setMusica(Boolean musica) {
		this.musica = musica;
	}

	@Column(name = "deporte")
	public Boolean getDeporte() {
		return this.deporte;
	}

	public void setDeporte(Boolean deporte) {
		this.deporte = deporte;
	}

	@Column(name = "cine")
	public Boolean getCine() {
		return this.cine;
	}

	public void setCine(Boolean cine) {
		this.cine = cine;
	}

	@Column(name = "montanya")
	public Boolean getMontanya() {
		return this.montanya;
	}

	public void setMontanya(Boolean montanya) {
		this.montanya = montanya;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<Pedidos> getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set<Pedidos> pedidoses) {
		this.pedidoses = pedidoses;
	}

}
